import SubNavegation from "../components/subNavegation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootProducts({ children }) {
  return (
      <div>
        <SubNavegation root={"/api"} arrayModules={["tags", "entidades"] } titleSep={"Json"} classColor={"blueMetalic"} />
        {children}
      </div>

  );
}
