import SubNavegation from "../components/subNavegation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LayoutTags({ children }) {
  return (
    <div>
      <SubNavegation
        root={"/tags"}
        arrayModules={["crear", "listado"]}
        titleSep={"Tags"}
        classColor={"purpleMetalic"}
      />
      {children}
    </div>
  );
}
