
import "../style/preRoot.css";
import Navegation from "./components/navegator.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navegation />
        {children}
      </body>
    </html>
  );
}
