import SubNavegation from "../components/subNavegation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootApi({ children }) {
  return (
      <div>
        <SubNavegation root={"/products"} arrayModules={["agregar", "listado"]} titleSep={"Crud"} classColor={"yellowMetalic"}/>
        {children}
      </div>

  );
}
